### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by GYskyfall** [Arrowstar/ksptot#17] opened 2019-01-12 06:41 UTC
<img width="776" alt="_20190112143118" src="https://user-images.githubusercontent.com/36434127/51070184-fb077500-1677-11e9-92b4-e70458e48777.png">
there some problems on the GUI ,also i can't set the launch window open

**Comment by Arrowstar** [comment] 2019-01-12 15:55
Thanks for the report. I'm going to need some more information in order to help.

What version are you on?
What went wrong? 
What did you expect to happen?
How do I reproduce it?

Thanks!

**Comment by Arrowstar** [comment] 2019-01-12 15:56
Oh wait are you talking about the text boxes on the right?

**Comment by Arrowstar** [comment] 2019-01-12 16:21
Try closing KSPTOT, changing your screen resolution to something with larger numbers,  and then rerunning KSPTOT.

Is this the only UI this happens in?

**Comment by Arrowstar** [comment] 2019-01-15 02:56
Is the picture you showed at 100% or 125%?

**Comment by GYskyfall** [comment] 2019-01-15 07:12
125%，also there is few problems,but much better than 150%

**Comment by Arrowstar** [comment] 2019-02-13 00:08
Turns out this is an issue with MATLAB's rendering engine and it doesn't look like there's much I can do with it.  Sorry!

**Closed by Arrowstar** 2019-02-13 00:08 UTC
