### ISSUE TITLE
Revs = 0 when actually >0

### ISSUE THREAD

**Issue by Gaiiden** [Arrowstar/ksptot#3] opened 2015-06-16 21:59 UTC
I haven't been able to work out a solid set of repro steps for this issue, but I have seen in pop up often while trying to recreate it. So it happens a lot, I just can't figure out a specific way to consistently trigger it.

The issue is that if I have a Coast event set to 1 for Revs Prior to Coast, at some point I will open the Edit Coast dialog for and it will show 0 for Revs Prior to Coast, yet Mission Architect will still render the orbit for 1 rev. If I just cancel out of the dialog nothing will change, but if I save the Rev value will reset to 0 as it was shown.

Here's the best I can give to set up MA for repro of the issue:

1 - set state by importing current active vessel data (the new feature you added).
2 - copy TA value
3 - save state
4 - create Coast to TA state and paste in TA value, set Revs to 1 and save

Once you've done that, sometimes I can immediately re-open the Edit Coast box and see 0 for Revs (even after creating a New file). If not, I've managed to trigger the issue in several other ways:

1 - edit the original state by importing new orbital data for the active vessel
2 - open the Edit Coast and changing the coast to Delta Time, then canceling out (Esc)
3 - various combinations of 1 & 2

**Comment by Arrowstar** [comment] 2016-05-04 01:16
Is this still an issue?

**Comment by KSAMissionCtrl** [comment] 2016-05-04 01:40
(Gaiiden here, new profile) I'm not sure what would have resolved it... but I haven't really been using KSPTOT much lately to have come across it consistently. I only know that it *was* occurring consistently enough for me to bother reporting it in the first place. It was a bit of a tricky thing to reproduce tho so unless you have an idea of what might be happening I'd say ignore it for a cold, rainy, otherwise useless day. It really didn't cause any harm - at least in the instances I came across it. Don't want to assume its harmless tho.

**Comment by Arrowstar** [comment] 2016-05-04 21:56
Looks like it's not a problem anymore.  I followed your instructions above with a variety of TAs (including funny ones at 0 and 180 degrees) and the number of revs sticks around.  Going to close this, re-report if you see it happen again in the next release. :)

**Closed by Arrowstar** 2016-05-04 21:56 UTC
