### ISSUE TITLE
Error when trying to use Parallel Script Optimization

### ISSUE THREAD

**Issue by mariohm1311** [Arrowstar/ksptot#6] opened 2016-02-09 16:22 UTC
Image cause I can't be bothered to write it: [http://i.imgur.com/wK7G2xl.png?1](url)

The Optimization Tool works perfectly with Parallel Optimization disabled, but this happens when you enable it. Created the exceptions for the firewall when enabling it for the first time, so I don't think it's that. 

PS: Mission file attached.

**Comment by mariohm1311** [comment] 2016-02-09 16:26
As attaching is not working, there goes a link to Mediafire: [http://www.mediafire.com/download/x4g9hj6xwzlxhxi/Eeloo_GravityAssist.zip](url)

**Comment by Arrowstar** [comment] 2016-05-04 21:54
Cannot reproduce, seems to work on my end, closing.

**Closed by Arrowstar** 2016-05-04 21:54 UTC
